swagger: '2.0'
info:
  title: Printers and Checks
  description: Api service for generate checks
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /neworder/:
    post:
      operationId: neworder_create
      description: |-
        POST запрос для генерації замовення, створення чеків для принтерів
            та запуску асинхронного воркера для генерації pdf
            Приклад запросу:
            {
            "point_id" : "1",
            "ingredients" : ["Cheese", "Салат", "Перець"],
            "order_number" : "672335189"

        }
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - neworder
    parameters: []
  /printer-list/:
    get:
      operationId: printer-list_list
      description: GET запрос для відображення всіх принтерів
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/PrinterList'
      tags:
        - printer-list
    parameters: []
  /printer-list/{id}/:
    get:
      operationId: printer-list_read
      description: |-
        GET запрос для відображення всих згенерованих чеків для конкретного принтера
        в headers в поле X-Api-Key потрібно передавати api-key принтеру
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - printer-list
    parameters:
      - name: id
        in: path
        required: true
        type: string
  /printer-list/{id}/{pk2}/:
    get:
      operationId: printer-list_read
      description: |-
        GET запрос міняє статус чека на "переглянутий"
        POST запрос друкує чек та міняє статус на "надрукований"
        permission with headers X-Api-Key: <your_printer_api_key>
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - printer-list
    post:
      operationId: printer-list_create
      description: |-
        GET запрос міняє статус чека на "переглянутий"
        POST запрос друкує чек та міняє статус на "надрукований"
        permission with headers X-Api-Key: <your_printer_api_key>
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - printer-list
    parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: pk2
        in: path
        required: true
        type: string
definitions:
  PrinterList:
    required:
      - name
      - check_type
      - checks
    type: object
    properties:
      pk:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Назва принтеру
        type: string
        maxLength: 50
        minLength: 1
      api_key:
        title: Ключ доступу до API
        type: string
        maxLength: 255
      check_type:
        title: Тип чеку який друкує принтер
        type: string
        enum:
          - kitchen
          - client
      point_id:
        title: Точка до якої привязаний принтер
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      checks:
        type: array
        items:
          type: integer
        uniqueItems: true
